// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/derailed/popeye/internal/linter (interfaces: Lister)

package linter

import (
	"reflect"
	"time"

	pegomock "github.com/petergtz/pegomock"
	v10 "k8s.io/api/core/v1"
	v1 "k8s.io/api/rbac/v1"
	v1beta1 "k8s.io/metrics/pkg/apis/metrics/v1beta1"
)

type MockLister struct {
	fail func(message string, callerSkip ...int)
}

func NewMockLister() *MockLister {
	return &MockLister{fail: pegomock.GlobalFailHandler}
}

func (mock *MockLister) ClusterHasMetrics() (bool, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ClusterHasMetrics", params, []reflect.Type{reflect.TypeOf((*bool)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 bool
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(bool)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchCMs() (*v10.ConfigMapList, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchCMs", params, []reflect.Type{reflect.TypeOf((**v10.ConfigMapList)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v10.ConfigMapList
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v10.ConfigMapList)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchCRBs() (*v1.ClusterRoleBindingList, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchCRBs", params, []reflect.Type{reflect.TypeOf((**v1.ClusterRoleBindingList)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v1.ClusterRoleBindingList
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v1.ClusterRoleBindingList)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchEPs() (*v10.EndpointsList, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchEPs", params, []reflect.Type{reflect.TypeOf((**v10.EndpointsList)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v10.EndpointsList
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v10.EndpointsList)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchNOs() (*v10.NodeList, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchNOs", params, []reflect.Type{reflect.TypeOf((**v10.NodeList)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v10.NodeList
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v10.NodeList)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchNSs() (*v10.NamespaceList, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchNSs", params, []reflect.Type{reflect.TypeOf((**v10.NamespaceList)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v10.NamespaceList
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v10.NamespaceList)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchNodesMetrics() ([]v1beta1.NodeMetrics, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchNodesMetrics", params, []reflect.Type{reflect.TypeOf((*[]v1beta1.NodeMetrics)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 []v1beta1.NodeMetrics
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].([]v1beta1.NodeMetrics)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchPOs() (*v10.PodList, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchPOs", params, []reflect.Type{reflect.TypeOf((**v10.PodList)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v10.PodList
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v10.PodList)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchPodsMetrics(_param0 string) ([]v1beta1.PodMetrics, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchPodsMetrics", params, []reflect.Type{reflect.TypeOf((*[]v1beta1.PodMetrics)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 []v1beta1.PodMetrics
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].([]v1beta1.PodMetrics)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchRBs() (*v1.RoleBindingList, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchRBs", params, []reflect.Type{reflect.TypeOf((**v1.RoleBindingList)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v1.RoleBindingList
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v1.RoleBindingList)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchSAs() (*v10.ServiceAccountList, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchSAs", params, []reflect.Type{reflect.TypeOf((**v10.ServiceAccountList)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v10.ServiceAccountList
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v10.ServiceAccountList)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchSECs() (*v10.SecretList, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchSECs", params, []reflect.Type{reflect.TypeOf((**v10.SecretList)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v10.SecretList
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v10.SecretList)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) FetchSVCs() (*v10.ServiceList, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("FetchSVCs", params, []reflect.Type{reflect.TypeOf((**v10.ServiceList)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v10.ServiceList
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v10.ServiceList)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) GetEndpoints(_param0 string) (*v10.Endpoints, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("GetEndpoints", params, []reflect.Type{reflect.TypeOf((**v10.Endpoints)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v10.Endpoints
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v10.Endpoints)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) GetPod(_param0 map[string]string) (*v10.Pod, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("GetPod", params, []reflect.Type{reflect.TypeOf((**v10.Pod)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *v10.Pod
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*v10.Pod)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) ListAllCRBs() (map[string]v1.ClusterRoleBinding, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ListAllCRBs", params, []reflect.Type{reflect.TypeOf((*map[string]v1.ClusterRoleBinding)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 map[string]v1.ClusterRoleBinding
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(map[string]v1.ClusterRoleBinding)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) ListAllPods() (map[string]v10.Pod, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ListAllPods", params, []reflect.Type{reflect.TypeOf((*map[string]v10.Pod)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 map[string]v10.Pod
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(map[string]v10.Pod)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) ListAllRBs() (map[string]v1.RoleBinding, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ListAllRBs", params, []reflect.Type{reflect.TypeOf((*map[string]v1.RoleBinding)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 map[string]v1.RoleBinding
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(map[string]v1.RoleBinding)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) ListCMs() (map[string]v10.ConfigMap, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ListCMs", params, []reflect.Type{reflect.TypeOf((*map[string]v10.ConfigMap)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 map[string]v10.ConfigMap
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(map[string]v10.ConfigMap)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) ListNS() (map[string]v10.Namespace, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ListNS", params, []reflect.Type{reflect.TypeOf((*map[string]v10.Namespace)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 map[string]v10.Namespace
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(map[string]v10.Namespace)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) ListNodes() ([]v10.Node, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ListNodes", params, []reflect.Type{reflect.TypeOf((*[]v10.Node)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 []v10.Node
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].([]v10.Node)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) ListNodesMetrics(_param0 []v10.Node, _param1 []v1beta1.NodeMetrics, _param2 NodesMetrics) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{_param0, _param1, _param2}
	pegomock.GetGenericMockFrom(mock).Invoke("ListNodesMetrics", params, []reflect.Type{})
}

func (mock *MockLister) ListPods() (map[string]v10.Pod, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ListPods", params, []reflect.Type{reflect.TypeOf((*map[string]v10.Pod)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 map[string]v10.Pod
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(map[string]v10.Pod)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) ListPodsMetrics(_param0 []v1beta1.PodMetrics, _param1 PodsMetrics) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{_param0, _param1}
	pegomock.GetGenericMockFrom(mock).Invoke("ListPodsMetrics", params, []reflect.Type{})
}

func (mock *MockLister) ListRBs() (map[string]v1.RoleBinding, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ListRBs", params, []reflect.Type{reflect.TypeOf((*map[string]v1.RoleBinding)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 map[string]v1.RoleBinding
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(map[string]v1.RoleBinding)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) ListSAs() (map[string]v10.ServiceAccount, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ListSAs", params, []reflect.Type{reflect.TypeOf((*map[string]v10.ServiceAccount)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 map[string]v10.ServiceAccount
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(map[string]v10.ServiceAccount)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) ListSecs() (map[string]v10.Secret, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ListSecs", params, []reflect.Type{reflect.TypeOf((*map[string]v10.Secret)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 map[string]v10.Secret
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(map[string]v10.Secret)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) ListServices() (map[string]v10.Service, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("ListServices", params, []reflect.Type{reflect.TypeOf((*map[string]v10.Service)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 map[string]v10.Service
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(map[string]v10.Service)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockLister) PodsNamespaces(_param0 []string) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockLister().")
	}
	params := []pegomock.Param{_param0}
	pegomock.GetGenericMockFrom(mock).Invoke("PodsNamespaces", params, []reflect.Type{})
}

func (mock *MockLister) VerifyWasCalledOnce() *VerifierLister {
	return &VerifierLister{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockLister) VerifyWasCalled(invocationCountMatcher pegomock.Matcher) *VerifierLister {
	return &VerifierLister{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockLister) VerifyWasCalledInOrder(invocationCountMatcher pegomock.Matcher, inOrderContext *pegomock.InOrderContext) *VerifierLister {
	return &VerifierLister{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockLister) VerifyWasCalledEventually(invocationCountMatcher pegomock.Matcher, timeout time.Duration) *VerifierLister {
	return &VerifierLister{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierLister struct {
	mock                   *MockLister
	invocationCountMatcher pegomock.Matcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierLister) ClusterHasMetrics() *Lister_ClusterHasMetrics_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ClusterHasMetrics", params, verifier.timeout)
	return &Lister_ClusterHasMetrics_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ClusterHasMetrics_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ClusterHasMetrics_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ClusterHasMetrics_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) FetchCMs() *Lister_FetchCMs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchCMs", params, verifier.timeout)
	return &Lister_FetchCMs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchCMs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchCMs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_FetchCMs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) FetchCRBs() *Lister_FetchCRBs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchCRBs", params, verifier.timeout)
	return &Lister_FetchCRBs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchCRBs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchCRBs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_FetchCRBs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) FetchEPs() *Lister_FetchEPs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchEPs", params, verifier.timeout)
	return &Lister_FetchEPs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchEPs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchEPs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_FetchEPs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) FetchNOs() *Lister_FetchNOs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchNOs", params, verifier.timeout)
	return &Lister_FetchNOs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchNOs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchNOs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_FetchNOs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) FetchNSs() *Lister_FetchNSs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchNSs", params, verifier.timeout)
	return &Lister_FetchNSs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchNSs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchNSs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_FetchNSs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) FetchNodesMetrics() *Lister_FetchNodesMetrics_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchNodesMetrics", params, verifier.timeout)
	return &Lister_FetchNodesMetrics_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchNodesMetrics_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchNodesMetrics_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_FetchNodesMetrics_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) FetchPOs() *Lister_FetchPOs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchPOs", params, verifier.timeout)
	return &Lister_FetchPOs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchPOs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchPOs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_FetchPOs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) FetchPodsMetrics(_param0 string) *Lister_FetchPodsMetrics_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchPodsMetrics", params, verifier.timeout)
	return &Lister_FetchPodsMetrics_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchPodsMetrics_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchPodsMetrics_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *Lister_FetchPodsMetrics_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierLister) FetchRBs() *Lister_FetchRBs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchRBs", params, verifier.timeout)
	return &Lister_FetchRBs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchRBs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchRBs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_FetchRBs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) FetchSAs() *Lister_FetchSAs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchSAs", params, verifier.timeout)
	return &Lister_FetchSAs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchSAs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchSAs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_FetchSAs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) FetchSECs() *Lister_FetchSECs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchSECs", params, verifier.timeout)
	return &Lister_FetchSECs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchSECs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchSECs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_FetchSECs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) FetchSVCs() *Lister_FetchSVCs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "FetchSVCs", params, verifier.timeout)
	return &Lister_FetchSVCs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_FetchSVCs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_FetchSVCs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_FetchSVCs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) GetEndpoints(_param0 string) *Lister_GetEndpoints_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GetEndpoints", params, verifier.timeout)
	return &Lister_GetEndpoints_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_GetEndpoints_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_GetEndpoints_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *Lister_GetEndpoints_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierLister) GetPod(_param0 map[string]string) *Lister_GetPod_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GetPod", params, verifier.timeout)
	return &Lister_GetPod_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_GetPod_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_GetPod_OngoingVerification) GetCapturedArguments() map[string]string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *Lister_GetPod_OngoingVerification) GetAllCapturedArguments() (_param0 []map[string]string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]map[string]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(map[string]string)
		}
	}
	return
}

func (verifier *VerifierLister) ListAllCRBs() *Lister_ListAllCRBs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListAllCRBs", params, verifier.timeout)
	return &Lister_ListAllCRBs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListAllCRBs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListAllCRBs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ListAllCRBs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) ListAllPods() *Lister_ListAllPods_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListAllPods", params, verifier.timeout)
	return &Lister_ListAllPods_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListAllPods_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListAllPods_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ListAllPods_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) ListAllRBs() *Lister_ListAllRBs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListAllRBs", params, verifier.timeout)
	return &Lister_ListAllRBs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListAllRBs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListAllRBs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ListAllRBs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) ListCMs() *Lister_ListCMs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListCMs", params, verifier.timeout)
	return &Lister_ListCMs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListCMs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListCMs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ListCMs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) ListNS() *Lister_ListNS_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListNS", params, verifier.timeout)
	return &Lister_ListNS_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListNS_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListNS_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ListNS_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) ListNodes() *Lister_ListNodes_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListNodes", params, verifier.timeout)
	return &Lister_ListNodes_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListNodes_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListNodes_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ListNodes_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) ListNodesMetrics(_param0 []v10.Node, _param1 []v1beta1.NodeMetrics, _param2 NodesMetrics) *Lister_ListNodesMetrics_OngoingVerification {
	params := []pegomock.Param{_param0, _param1, _param2}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListNodesMetrics", params, verifier.timeout)
	return &Lister_ListNodesMetrics_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListNodesMetrics_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListNodesMetrics_OngoingVerification) GetCapturedArguments() ([]v10.Node, []v1beta1.NodeMetrics, NodesMetrics) {
	_param0, _param1, _param2 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1], _param1[len(_param1)-1], _param2[len(_param2)-1]
}

func (c *Lister_ListNodesMetrics_OngoingVerification) GetAllCapturedArguments() (_param0 [][]v10.Node, _param1 [][]v1beta1.NodeMetrics, _param2 []NodesMetrics) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([][]v10.Node, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.([]v10.Node)
		}
		_param1 = make([][]v1beta1.NodeMetrics, len(params[1]))
		for u, param := range params[1] {
			_param1[u] = param.([]v1beta1.NodeMetrics)
		}
		_param2 = make([]NodesMetrics, len(params[2]))
		for u, param := range params[2] {
			_param2[u] = param.(NodesMetrics)
		}
	}
	return
}

func (verifier *VerifierLister) ListPods() *Lister_ListPods_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListPods", params, verifier.timeout)
	return &Lister_ListPods_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListPods_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListPods_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ListPods_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) ListPodsMetrics(_param0 []v1beta1.PodMetrics, _param1 PodsMetrics) *Lister_ListPodsMetrics_OngoingVerification {
	params := []pegomock.Param{_param0, _param1}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListPodsMetrics", params, verifier.timeout)
	return &Lister_ListPodsMetrics_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListPodsMetrics_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListPodsMetrics_OngoingVerification) GetCapturedArguments() ([]v1beta1.PodMetrics, PodsMetrics) {
	_param0, _param1 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1], _param1[len(_param1)-1]
}

func (c *Lister_ListPodsMetrics_OngoingVerification) GetAllCapturedArguments() (_param0 [][]v1beta1.PodMetrics, _param1 []PodsMetrics) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([][]v1beta1.PodMetrics, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.([]v1beta1.PodMetrics)
		}
		_param1 = make([]PodsMetrics, len(params[1]))
		for u, param := range params[1] {
			_param1[u] = param.(PodsMetrics)
		}
	}
	return
}

func (verifier *VerifierLister) ListRBs() *Lister_ListRBs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListRBs", params, verifier.timeout)
	return &Lister_ListRBs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListRBs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListRBs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ListRBs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) ListSAs() *Lister_ListSAs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListSAs", params, verifier.timeout)
	return &Lister_ListSAs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListSAs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListSAs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ListSAs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) ListSecs() *Lister_ListSecs_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListSecs", params, verifier.timeout)
	return &Lister_ListSecs_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListSecs_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListSecs_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ListSecs_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) ListServices() *Lister_ListServices_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "ListServices", params, verifier.timeout)
	return &Lister_ListServices_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_ListServices_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_ListServices_OngoingVerification) GetCapturedArguments() {
}

func (c *Lister_ListServices_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierLister) PodsNamespaces(_param0 []string) *Lister_PodsNamespaces_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "PodsNamespaces", params, verifier.timeout)
	return &Lister_PodsNamespaces_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Lister_PodsNamespaces_OngoingVerification struct {
	mock              *MockLister
	methodInvocations []pegomock.MethodInvocation
}

func (c *Lister_PodsNamespaces_OngoingVerification) GetCapturedArguments() []string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *Lister_PodsNamespaces_OngoingVerification) GetAllCapturedArguments() (_param0 [][]string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([][]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.([]string)
		}
	}
	return
}
