project_name: popeye

before:
  hooks:
    - go mod download

release:
  prerelease: false

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/derailed/popeye/cmd.version={{.Version}}
      - -s -w -X github.com/derailed/popeye/cmd.commit={{.Commit}}
      - -s -w -X github.com/derailed/popeye/cmd.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: popeye
    repository:
      owner: derailed
      name: popeye-homebrew-tap
    commit_author:
      name: derailed
      email: fernand@imhotep.io
    folder: Formula
    homepage: https://imhotep.io/popeye
    description: A Kubernetes Cluster sanitizer and linter.
    test: |
      system "popeye version"
