project_name: popeye
before:
  hooks:
    - go mod download
    # - go generate ./...
release:
  prerelease: true
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X github.com/derailed/popeye/cmd.version={{.Version}} -X github.com/derailed/popeye/cmd.commit={{.Commit}} -X github.com/derailed/popeye/cmd.date={{.Date}}
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    bit: Arm
    bitv6: Arm6
    bitv7: Arm7
    386: i386
    amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrew
brew:
  name: popeye
  github:
    owner: derailed
    name: popeye-homebrew-tap
  commit_author:
    name: derailed
    email: fernand@imhotep.io
  folder: Formula
  homepage: https://imhotep.io/popeye
  description: A Kubernetes Cluster sanitizer and linter.
  test: |
    system "popeye version"

# Snapcraft
snapcraft:
  name: popeye
  summary: A Kubernetes Cluster sanitizer and linter.
  description: |
    Popeye scans your Kubernetes clusters and reports potential resource issues.
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  publish: true
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Tux
    bit: Arm
    bitv6: Arm6
    bitv7: Arm7
  grade: stable
  confinement: strict
  apps:
    popeye:
      plugs: ["home", "network", "personal-files"]
  plugs:
    personal-files:
      read:
      - $HOME/.k9s
      - $HOME/.kube
      write:
      - $HOME/.k9s
