version: 2

project_name: popeye

before:
  hooks:
    - go mod download

release:
  prerelease: false

env:
  - CGO_ENABLED=0

builds:
  - id: linux
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
      # - arm
      - ppc64le
      - s390x
    # goarm:
    #   - 7
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/derailed/popeye/cmd.version={{.Version}}
      - -s -w -X github.com/derailed/popeye/cmd.commit={{.Commit}}
      - -s -w -X github.com/derailed/popeye/cmd.date={{.Date}}

  - id: osx
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/derailed/popeye/cmd.version={{.Version}}
      - -s -w -X github.com/derailed/popeye/cmd.commit={{.Commit}}
      - -s -w -X github.com/derailed/popeye/cmd.date={{.Date}}

  - id: windows
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/derailed/popeye/cmd.version={{.Version}}
      - -s -w -X github.com/derailed/popeye/cmd.commit={{.Commit}}
      - -s -w -X github.com/derailed/popeye/cmd.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.sha256"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: popeye
    repository:
      owner: derailed
      name: popeye-homebrew-tap
    commit_author:
      name: derailed
      email: fernand@imhotep.io
    directory: Formula
    homepage: https://imhotep.io/popeye
    description: A Kubernetes Cluster sanitizer and linter!
    test: |
      system "popeye version"

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    maintainer: Fernand Galiana
    homepage: https://popeyecli.io
    description: A Kubernetes Cluster sanitizer and linter!
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/popeye/copyright
        file_info:
          mode: 0644

sboms:
  - artifacts: archive