project_name: popeye

before:
  hooks:
    - go mod download

release:
  prerelease: "false"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - darwin
      # - windows
    goarch:
      - amd64
      # - arm
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/derailed/popeye/cmd.version={{.Version}} -X github.com/derailed/popeye/cmd.commit={{.Commit}} -X github.com/derailed/popeye/cmd.date={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    # replacements:
    #   darwin: Darwin
    #   linux: Linux
    #   windows: Windows
    #   bit: Arm
    #   bitv6: Arm6
    #   bitv7: Arm7
    #   amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrew
# brews:
#   - name: popeye
#     tap:
#       owner: derailed
#       name: popeye-homebrew-tap
#     commit_author:
#       name: derailed
#       email: fernand@imhotep.io
#     folder: Formula
#     homepage: https://imhotep.io/popeye
#     description: A Kubernetes Cluster sanitizer and linter.
#     test: |
#       system "popeye version"

dockers:
  - image_templates:
      - "ghcr.io/macmiranda/popeye:{{.Version}}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=A Kubernetes cluster resource sanitizer"
      - "--platform=linux/amd64"
    use: buildx
    dockerfile: Dockerfile

  - image_templates:
      - "ghcr.io/macmiranda/popeye:{{.Version}}-arm64v8"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=A Kubernetes cluster resource sanitizer"
      - "--platform=linux/arm64/v8"
    use: buildx
    dockerfile: Dockerfile

docker_manifests:
- name_template: "ghcr.io/macmiranda/popeye:{{ .Version }}"
  image_templates:
  - "ghcr.io/macmiranda/popeye:{{ .Version }}-amd64"
  - "ghcr.io/macmiranda/popeye:{{ .Version }}-arm64v8"
