{
 "title": "PopDash",
 "description": "Popeye cluster scan report dashboard",
 "tags": [ "popeye" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "topk", "label": "TopK", "query": "10,20,50" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(popeye_code_total,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(popeye_code_total,namespace)"
    }
   },
   {
    "name": "linter",
    "label": "Linter",
    "query": {
     "query": "label_values(popeye_code_total,linter)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "options": {
    "content": "<img style=\"float:left;max-width:175px;border-radius:10px;-webkit-filter:drop-shadow(8px 8px 10px #373831);filter:drop-shadow(8px 8px 10px #373831);\" src=\"https://github.com/derailed/popeye/raw/master/assets/popeye_logo.png\" alt=\"popeye-logo\"/>\n<span style=\"float:left;color:greenyellow;font-size:4em;font-family:Gill Sans\">Popeye K8s Cluster Scan</span>\n<p style=\"font-style:italic;\">Biffs`em and Buffs`em!</p>\n\n"
   }
  },
  { "title": "Grades", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "popeye_cluster_score{scan!=\"\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{cluster}}-{{namespace}} ({{grade}})"
    }
   ]
  },
  { "title": "ScanCodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "topk($topk, popeye_code_total{severity=\"error\", cluster=~\"$cluster\", namespace=~\"$namespace\", linter=~\"$linter\"}) by (namespace, linter)",
     "legendFormat": "[POP-{{code}}] {{linter}}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "topk($topk, popeye_code_total{severity=\"warn\", cluster=~\"$cluster\", namespace=~\"$namespace\", linter=~\"$linter\"}) by (namespace, linter)",
     "legendFormat": "[POP-{{code}}] {{linter}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Infos",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "topk($topk, popeye_code_total{severity=\"info\", cluster=~\"$cluster\", namespace=~\"$namespace\", linter=~\"$linter\"}) by (namespace, linter)",
     "legendFormat": "[POP-{{code}}] {{linter}}"
    }
   ]
  },
  {
   "title": "Severities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "stat",
     "gridPos": { "h": 15, "w": 8, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "popeye_severity_total{severity=\"error\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{cluster}} ({{namespace}})"
      }
     ]
    },
    {
     "title": "Warnings",
     "type": "stat",
     "gridPos": { "h": 15, "w": 8, "x": 8, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "popeye_severity_total{severity=\"warn\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{cluster}} ({{namespace}})"
      }
     ]
    },
    {
     "title": "Infos",
     "type": "stat",
     "description": "Popeye severity total scores.",
     "gridPos": { "h": 15, "w": 8, "x": 16, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($topk, popeye_severity_total{severity=\"info\", cluster=~\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  { "title": "Linters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Errors",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk($topk, sum by (linter) (popeye_linter_tally_total{severity=\"error\", cluster=~\"$cluster\", linter=~\"$linter\"})) by (cluster, linter)",
     "legendFormat": "{{linter}}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "topk($topk, sum by (linter) (popeye_linter_tally_total{severity=\"warn\", cluster=~\"$cluster\", linter=~\"$linter\"})) by (cluster, linter)",
     "legendFormat": "{{linter}}"
    }
   ]
  },
  {
   "title": "Info",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "topk($topk, sum by (linter) (popeye_linter_tally_total{severity=\"info\", cluster=~\"$cluster\", linter=~\"$linter\"})) by (cluster, linter)",
     "legendFormat": "{{linter}}"
    }
   ]
  }
 ]
}