apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: popeye
spec:
  homepage: https://popeyecli.io
  shortDescription: 🧭 A Kubernetes cluster resource sanitizer
  version: v0.7.1
  description: |
    Popeye is a utility that scans live Kubernetes clusters and reports
    potential issues with deployed resources and configurations.
    It sanitizes your cluster based on what's deployed and not what's
    sitting on disk. By scanning your cluster, it detects misconfigurations
    and ensure best practices are in place thus preventing potential future
    headaches. It aims at reducing the cognitive overload one faces when
    operating a Kubernetes cluster in the wild. Furthermore, if your
    cluster employs a metric-server, it reports potential resources
    over/under allocations and attempts to warn you should your cluster
    run out of capacity.

    Popeye is a readonly tool, it does not alter any of your Kubernetes
    resources in any way!
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/derailed/popeye/releases/download/v0.7.1/popeye_Darwin_x86_64.tar.gz
      sha256: e5f84baafbfa7170a02c0777e0dac5e7009c19c4b487d512b8f0e21298f10484
      files:
        - from: popeye
          to: kubectl-popeye
        - from: LICENSE
          to: "."
      bin: kubectl-popeye
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/derailed/popeye/releases/download/v0.7.1/popeye_Linux_x86_64.tar.gz
      sha256: d4d7d776e05a0de5b681cb5421e3d9884103b902142313d8371e4f5e6b3d66dd
      files:
        - from: popeye
          to: kubectl-popeye
        - from: LICENSE
          to: "."
      bin: kubectl-popeye
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/derailed/popeye/releases/download/v0.7.1/popeye_Windows_x86_64.tar.gz
      sha256: a743da9715abaf320d3b9391bd0cff8f914300d0cd289a733a29224fde72fea7
      files:
        - from: popeye.exe
          to: kubectl-popeye.exe
        - from: LICENSE
          to: "."
      bin: kubectl-popeye.exe
