{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "popeye.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "popeye.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- else }}
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: popeye
  namespace: {{ .Values.namespace }}
{{- end }}
