---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: popeye-reports
  name: popeye-reports
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: popeye-reports

