# A Sample Popeye configuration.
popeye:
  # Allocations ratios current to resources.
  allocations:
    cpu:
      over: 200
      under: 50
    memory:
      over: 200
      under: 50

  # Excludes
  excludes:
    node:
      - name: n1
        codes:
          - 100
    namespace:
      - name: kube-system
      - name: kube-node-lease
      - name: kube-public
      - name: istio-system
    service:
      - name: default/dictionary

  # Node...
  node:
    limits:
      cpu: 90
      memory: 80

  # Pod...
  pod:
    limits:
      cpu: 80
      memory: 75
    restarts: 3
